### ISSUE TITLE
Run `opa test` as part of build

### ISSUE THREAD

**Issue by anderseknert** [XenitAB/github-actions#45]
This is easy to setup using the new [setup-opa](https://github.com/open-policy-agent/setup-opa) GitHub Action 😃 

```yaml
name: Run OPA Tests  
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: Run OPA Tests 
      run: opa test tests/*.rego -v
```
